# Generated by Django 2.0.7 on 2018-10-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalism', '0002_auto_20181014_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['publication']},
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('publication', 'title')},
        ),
    ]
